version: '3' 

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    environment:
      - TZ=/Europe/Madrid
    
    volumes:
      # 1. Volumen de Configuración:
      - ./config:/config
      
      # 2. Volumen de Hora:
      - /etc/localtime:/etc/localtime:ro

    ports:
      - "8123:8123" 
    
    # Política de reinicio
    restart: unless-stopped
    
  # mosquitto
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      # Puerto estándar de MQTT sin cifrar
      - "1883:1883"
    volumes:
      # Persiste la configuración de Mosquitto
      - ./mosquitto/config:/mosquitto/config
      # Persiste los datos de las colas (mensajes retenidos)
      - ./mosquitto/data:/mosquitto/data
      # Persiste los logs
      - ./mosquitto/log:/mosquitto/log