version: '3' 

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    environment:
      - TZ=/Europe/Madrid
    
    volumes:
      # 1. Volumen de Configuración:
      - ./config:/config
      
      # 2. Volumen de Hora:
      - /etc/localtime:/etc/localtime:ro

    ports:
      - "8123:8123" 
    
    # Política de reinicio
    restart: unless-stopped
    
# Descubrir dispositivos de red
# network_mode: host