# 1. Coordenadas de tu casa (ejemplo)
home_latitude: 37.18817
home_longitude: -3.60667

# 2. Clave para una API externa (ejemplo)
openweather_api_key: "pass1234"

# 3. Contrase√±a para el router/MQTT (ejemplo)
mqtt_password: "pass1234"
